### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by fafaraway** [scrable/oUF_Farva#1]
hey scrable
just wonder how to alter this part font
btw, really love your aesthetic 👍 

![20180903044051](https://user-images.githubusercontent.com/156806/44960531-f2699a00-af33-11e8-9c31-f161b875f4ed.png)

**Comment by scrable** [comment]
I am setting that font using addon PhanxFont. The specific object for that font is called SystemFont_Shadow_Small. This object is also tied to other addons and other parts of Blizzard UI like chat tab font, so if you have different fonts and different sizes for these objects you will need a different solution.

**Comment by fafaraway** [comment]
thanks for explain 👍
